AWSTemplateFormatVersion: "2010-09-09"
Description: "Document for all Iam roles and permissions"

Parameters:
  SuspName:
    Type: String
    Description: Prefix for naming resources

Resources:
  # IAM Role for Maintenance Window
  SSMMaintenanceWindowRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "${SuspName}-SSMMaintenanceWindowRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ssm.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

Outputs:
  SSMMaintenanceWindowRoleName:
    Description: "The name of the created IAM Role"
    Value: !Ref SSMMaintenanceWindowRole
    Export:
      Name: !Sub "${SuspName}-SSMMaintenanceWindowRoleName"

  SSMMaintenanceWindowRoleArn:
    Description: "The ARN of the created IAM Role"
    Value: !GetAtt SSMMaintenanceWindowRole.Arn
    Export:
      Name: !Sub "${SuspName}-SSMMaintenanceWindowRoleArn"
